/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: vmmaniac (https://sketchfab.com/vmmaniac)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-flying-fluttering-butterfly-loop-v20-71f86ae0a1c148a69fe3327397fff5ee
Title: Animated Flying Fluttering Butterfly Loop v2.0
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import butterflyModel from './../assets/3d/butterfly.glb'

export default function Model({ currentAnimation, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(
    butterflyModel
  )
  const { actions } = useAnimations(animations, group);

  // This effect will run whenever the currentAnimation prop changes
  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());

    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  }, [actions, currentAnimation]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode0_159" scale={0.01}>
                <group name="skeletal3_158">
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <skinnedMesh
                      name="Object_8"
                      geometry={nodes.Object_8.geometry}
                      material={materials.Material_0}
                      skeleton={nodes.Object_8.skeleton}
                    />
                    <group name="butterfly2_157" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}





